"""Initial migration

Revision ID: 001_initial
Revises: 
Create Date: 2024-01-01 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scansession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('root_path', sa.String(), nullable=False),
    sa.Column('total_files_scanned', sa.Integer(), nullable=False),
    sa.Column('total_size_scanned', sa.Integer(), nullable=False),
    sa.Column('scan_duration_seconds', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scanresult',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_mtime', sa.Float(), nullable=False),
    sa.Column('is_directory', sa.Boolean(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('classification', sa.String(), nullable=False),
    sa.Column('age_score', sa.Integer(), nullable=False),
    sa.Column('age_reason', sa.String(), nullable=False),
    sa.Column('version_score', sa.Integer(), nullable=False),
    sa.Column('version_reason', sa.String(), nullable=False),
    sa.Column('process_score', sa.Integer(), nullable=False),
    sa.Column('process_reason', sa.String(), nullable=False),
    sa.Column('project_score', sa.Integer(), nullable=False),
    sa.Column('project_reason', sa.String(), nullable=False),
    sa.Column('rule_matches', sa.String(), nullable=False),
    sa.Column('marked_for_deletion', sa.Boolean(), nullable=False),
    sa.Column('deletion_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['scansession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deletionaudit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('file_existed', sa.Boolean(), nullable=False),
    sa.Column('file_size_at_action', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['scanresult.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deletionaudit')
    op.drop_table('scanresult')
    op.drop_table('scansession')
    # ### end Alembic commands ###
